<?php
/**
 * PDF Generator for Forecast Reports
 * Uses TCPDF library for PDF generation
 */

function generateForecastPDF($forecast_data, $forecast_period, $sort_by, $output_path, $sales_history = [], $forecast_history = []) {
    // Check if TCPDF is available, if not use HTML-based PDF
    if (class_exists('TCPDF')) {
        generateForecastPDF_TCPDF($forecast_data, $forecast_period, $sort_by, $output_path, $sales_history, $forecast_history);
    } else {
        // Fallback: Generate HTML that can be printed to PDF
        generateForecastPDF_HTML($forecast_data, $forecast_period, $sort_by, $output_path, $sales_history, $forecast_history);
    }
}

function generateForecastPDF_HTML($forecast_data, $forecast_period, $sort_by, $output_path, $sales_history = [], $forecast_history = []) {
    // Change extension to .html for print-to-PDF
    $output_path = preg_replace('/\.pdf$/', '.html', $output_path);
    $html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Forecast Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #2563eb;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #2563eb;
            margin: 0;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .info-section {
            margin-bottom: 20px;
            padding: 15px;
            background: #f3f4f6;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #2563eb;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        tr.highlight {
            background-color: #fef3c7 !important;
            font-weight: bold;
        }
        .highlight-badge {
            background-color: #f59e0b;
            color: white;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 0.85em;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 0.9em;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
        .summary-box {
            background: #eff6ff;
            border-left: 4px solid #2563eb;
            padding: 15px;
            margin: 20px 0;
        }
        @media print {
            body { margin: 0; }
            .no-print { display: none; }
        }
        .print-button {
            text-align: center;
            margin: 20px 0;
        }
        .print-button button {
            background-color: #2563eb;
            color: white;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
        }
        .print-button button:hover {
            background-color: #1d4ed8;
        }
    </style>
    <script>
        function printPDF() {
            window.print();
        }
    </script>
</head>
<body>
    <div class="print-button no-print">
        <button onclick="printPDF()">Print / Save as PDF</button>
    </div>
    <div class="header">
        <h1>Demand Forecast Report</h1>
        <p>Generated on ' . date('F d, Y h:i A') . '</p>
        <p>Forecast Period: ' . date('F d, Y', strtotime($forecast_period)) . '</p>
    </div>
    
    <div class="info-section">
        <strong>Report Summary:</strong><br>
        Total Products Forecasted: ' . count($forecast_data) . '<br>
        Sort By: ' . ucfirst($sort_by) . '<br>
        Generated By: ' . ($_SESSION['full_name'] ?? 'System') . '
    </div>';
    
    if (!empty($forecast_data)) {
        // Find highest values for highlighting
        $highest_quantity = 0;
        $highest_sales = 0;
        foreach ($forecast_data as $item) {
            if ($item['total_quantity'] > $highest_quantity) {
                $highest_quantity = $item['total_quantity'];
            }
            if ($item['total_sales'] > $highest_sales) {
                $highest_sales = $item['total_sales'];
            }
        }
        
        $html .= '
    <div class="summary-box">
        <strong>Top Performers:</strong><br>
        Highest Quantity: ' . number_format($highest_quantity, 2) . ' units<br>
        Highest Sales: ₱' . number_format($highest_sales, 2) . '
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Forecasted Quantity</th>
                <th>Historical Quantity</th>
                <th>Total Sales (₱)</th>
                <th>Avg Price (₱)</th>
                <th>Confidence Level</th>
            </tr>
        </thead>
        <tbody>';
        
        foreach ($forecast_data as $index => $item) {
            $is_highlight = false;
            if ($sort_by == 'quantity' && $item['total_quantity'] == $highest_quantity) {
                $is_highlight = true;
            } elseif ($sort_by == 'sales' && $item['total_sales'] == $highest_sales) {
                $is_highlight = true;
            }
            
            $row_class = $is_highlight ? 'highlight' : '';
            $badge = $is_highlight ? '<span class="highlight-badge">TOP</span>' : '';
            
            $html .= '
            <tr class="' . $row_class . '">
                <td>' . htmlspecialchars($item['product_name']) . ' ' . $badge . '</td>
                <td>' . number_format($item['forecasted_quantity'], 2) . '</td>
                <td>' . number_format($item['total_quantity'], 2) . '</td>
                <td>₱' . number_format($item['total_sales'], 2) . '</td>
                <td>₱' . number_format($item['avg_price'], 2) . '</td>
                <td>' . number_format($item['confidence_level'], 1) . '%</td>
            </tr>';
        }
        
        $html .= '
        </tbody>
    </table>';
    }
    
    // Add Historical Sales and Trends section
    if (!empty($sales_history) || !empty($forecast_history)) {
        $html .= '
    <h2 style="margin-top: 40px; color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px;">Historical Sales & Trends</h2>
    
    <div class="info-section">
        <strong>Sales History Summary:</strong><br>';
        
        if (!empty($sales_history)) {
            $total_sales_qty = array_sum(array_column($sales_history, 'total_quantity'));
            $avg_sales_price = 0;
            $price_count = 0;
            foreach ($sales_history as $item) {
                if (isset($item['avg_price']) && $item['avg_price'] > 0) {
                    $avg_sales_price += $item['avg_price'];
                    $price_count++;
                }
            }
            $avg_sales_price = $price_count > 0 ? $avg_sales_price / $price_count : 0;
            
            $html .= 'Total Historical Quantity: ' . number_format($total_sales_qty, 2) . ' units<br>';
            $html .= 'Average Price: ₱' . number_format($avg_sales_price, 2) . '<br>';
        }
        
        if (!empty($forecast_history)) {
            $total_forecast_qty = array_sum(array_column($forecast_history, 'total_forecasted_quantity'));
            $avg_confidence = 0;
            $conf_count = 0;
            foreach ($forecast_history as $item) {
                if (isset($item['avg_confidence']) && $item['avg_confidence'] > 0) {
                    $avg_confidence += $item['avg_confidence'];
                    $conf_count++;
                }
            }
            $avg_confidence = $conf_count > 0 ? $avg_confidence / $conf_count : 0;
            
            $html .= 'Total Forecasted Quantity: ' . number_format($total_forecast_qty, 2) . ' units<br>';
            $html .= 'Average Confidence Level: ' . number_format($avg_confidence, 1) . '%<br>';
        }
        
        $html .= '
    </div>
    
    <table style="margin-top: 20px;">
        <thead>
            <tr>
                <th>Period</th>
                <th>Historical Sales (Qty)</th>';
        
        if (!empty($sales_history[0]['avg_price'])) {
            $html .= '<th>Avg Price (₱)</th>';
        }
        
        $html .= '<th>Forecasted Demand (Qty)</th>';
        
        if (!empty($forecast_history[0]['avg_confidence'])) {
            $html .= '<th>Avg Confidence (%)</th>';
        }
        
        $html .= '
            </tr>
        </thead>
        <tbody>';
        
        // Combine sales and forecast data by period
        $combined_data = [];
        $periods = [];
        
        foreach ($sales_history as $item) {
            $period = $item['period'];
            $periods[$period] = true;
            $combined_data[$period] = [
                'period' => $period,
                'sales_quantity' => $item['total_quantity'] ?? 0,
                'avg_price' => $item['avg_price'] ?? 0
            ];
        }
        
        foreach ($forecast_history as $item) {
            $period = $item['period'];
            $periods[$period] = true;
            if (!isset($combined_data[$period])) {
                $combined_data[$period] = [
                    'period' => $period,
                    'sales_quantity' => 0,
                    'avg_price' => 0
                ];
            }
            $combined_data[$period]['forecast_quantity'] = $item['total_forecasted_quantity'] ?? 0;
            $combined_data[$period]['avg_confidence'] = $item['avg_confidence'] ?? 0;
        }
        
        krsort($periods);
        $sorted_periods = array_keys($periods);
        
        foreach ($sorted_periods as $period) {
            $data = $combined_data[$period] ?? ['period' => $period, 'sales_quantity' => 0, 'forecast_quantity' => 0, 'avg_price' => 0, 'avg_confidence' => 0];
            $html .= '
            <tr>
                <td>' . htmlspecialchars($data['period']) . '</td>
                <td>' . number_format($data['sales_quantity'], 2) . '</td>';
            
            if (!empty($sales_history[0]['avg_price'])) {
                $html .= '<td>₱' . number_format($data['avg_price'], 2) . '</td>';
            }
            
            $html .= '<td>' . number_format($data['forecast_quantity'] ?? 0, 2) . '</td>';
            
            if (!empty($forecast_history[0]['avg_confidence'])) {
                $html .= '<td>' . number_format($data['avg_confidence'] ?? 0, 1) . '%</td>';
            }
            
            $html .= '
            </tr>';
        }
        
        $html .= '
        </tbody>
    </table>';
    }
    
    $html .= '
    <div class="footer">
        <p>This report was automatically generated by the Supply Chain Management System.</p>
        <p>For questions or concerns, please contact the system administrator.</p>
    </div>
</body>
</html>';
    
    file_put_contents($output_path, $html);
}

function generateForecastPDF_TCPDF($forecast_data, $forecast_period, $sort_by, $output_path, $sales_history = [], $forecast_history = []) {
    // TCPDF implementation would go here if library is available
    // For now, fallback to HTML
    generateForecastPDF_HTML($forecast_data, $forecast_period, $sort_by, $output_path, $sales_history, $forecast_history);
}
?>

